version: "3.9"

services:
  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "${PORT}:${DOCKER_PORT}"
    volumes:
      - ./app/private:/app/private
      - /app/private/ui
