version: "3.9"

services:
  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "${PORT}:${DOCKER_PORT}"
    volumes:
      - ./app:/app
    environment:
      - PORT=${PORT}
      - DOCKER_PORT=${DOCKER_PORT}
      - DOCS_DIR=${DOCS_DIR}